name: Books-Api Pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml  
    with:
      project-name: "books-api"  

  build:
    needs: ci  
    uses: ./.github/workflows/build.yml  
    with:
      project-name: "books-api"  
